services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - db.env
    volumes:
      - sql_data:/var/opt/mssql

  api:
    image: ghcr.io/artemkostiuchenko/blog-post-api:latest
    restart: always
    env_file:
      - api.env
    depends_on:
      - db
    volumes:
      - static_files:/app/static

  app:
    image: ghcr.io/artemkostiuchenko/blog-post-front:latest
    ports:
      - "8080:80"
    restart: always

volumes:
  sql_data:
  static_files:

networks:
  network:
    driver: bridge
