services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - db.env
    volumes:
      - sql_data:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: TestWebApi/Dockerfile
    restart: always
    env_file:
      - api.env
    depends_on:
      - db
    volumes:
      - static_files:/app/static

  app:
    image: vite_react
    ports:
      - "8080:80"
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"

volumes:
  sql_data:
  static_files:

networks:
  network:
    driver: bridge
